services:
  server:
      image: fortinet-hugo:latest
      command: server --watch -DF --poll 700ms --verbose
      volumes:
        - ./content:/home/CentralRepo/content
        - ./config.toml:/home/CentralRepo/config.toml
        - ./layouts:/home/UserRepo/layouts
      ports:
        - 1313:1313